name: Deploy Frontend (React / Vite)

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout de código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          # cache: 'npm'

      - name: Instalar dependencias y compilar
        run: |
          npm install
          npm run build

      - name: Instalar cliente Cloudflare
        run: |
          curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared.deb

      - name: Transferir carpeta dist/ a Mictlán vía SCP
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Transferir carpeta dist/ a Mictlán mediante SCP nativo
        run: |
          scp -o StrictHostKeyChecking=no \
              -o ProxyCommand="cloudflared access ssh --hostname %h" \
              -r dist/* ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:${{ secrets.PROJECT_PATH }}/

      - name: Recargar servidor Nginx en Mictlán
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          proxy_command: cloudflared access ssh --hostname %h
          script: |
            cd ${{ secrets.PROJECT_PATH }}

            # Extraer la rama actual y los primeros 7 caracteres del SHA del commit
            BRANCH=${{ github.ref_name }}
            COMMIT_SHA=${{ github.sha }}
            SHORT_SHA=${COMMIT_SHA:0:7}

            # Pasar el tag a Docker Compose al construir/levantar
            IMAGE_TAG=$SHORT_SHA docker compose up -d --build

            # Limpiar versiones e imágenes viejas sin usar para evitar llenar el disco
            docker image prune -f